clay-land/teed-up

config/routes.rb
Please take a look at the routes I created
=> Bag, Rental, Review routes added

app/models/bag.rb, db/migrate/20210517221320_create_bags.rb, db/schema.rb, test/models/bag_test.rb
**Bag Model**
**Migration File**
=> created Bag model with reference and validations

app/models/user.rb
**User model**
has_many relationship added to User model to connect with Bag model
**Bag model**
=> added has_many relationship to User model

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_flashes.html.erb, app/views/shared/_navbar.html.erb
Devise login and logout links are in the navbar. Other links in the dropdown menu need to be updated as we create the views
=> Add devise links navbar

.gitignore, Gemfile, Gemfile.lock, app/controllers/bags_controller.rb, app/models/bag.rb, app/views/bags/edit.html.erb, app/views/bags/new.html.erb, app/views/bags/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20210518182510_create_active_storage_tables.active_storage.rb, db/schema.rb
Added cloudinary, set up heroku config etc.
=> Add cloudinary

app/models/bag.rb, app/models/rental.rb, app/models/user.rb, db/migrate/20210518175107_create_rentals.rb, db/schema.rb, test/models/rental_test.rb
removed screenshot: schema not correct reflection of post-rental migration
see code in commits
=> Create rentals model

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/bags_controller.rb, app/policies/application_policy.rb, app/policies/bag_policy.rb, test/policies/bag_policy_test.rb
**Application and Bag Policies**
=> Add pundit to bag controller

app/views/bags/index.html.erb, app/views/bags/show.html.erb
**Index view - links added to Bag names**
**Show page**
=> added link to Bags#show to Bags#indx

app/assets/stylesheets/components/_bag_form.scss, app/assets/stylesheets/components/_index.scss, app/views/bags/edit.html.erb, app/views/bags/new.html.erb, app/views/bags/show.html.erb
=> Reformatted the 'new' and 'edit' Forms for bags

app/controllers/rentals_controller.rb, app/views/rentals/new.html.erb, app/views/rentals/show.html.erb, test/controllers/rentals_controller_test.rb
**Rentals controller with #new action created**
=> Create rentals controller

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/_card.html.erb, app/views/pages/home.html.erb
=> Created the cards in the home view

app/controllers/rentals_controller.rb, app/policies/rental_policy.rb, app/views/bags/show.html.erb, app/views/rentals/show.html.erb, test/policies/rental_policy_test.rb
**Created rental - Show page**
=> Rentals show new and create actions

app/models/bag.rb
Tested validation locally in console:
=> added validation on Bag rate, must be greater or equal to 0

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
=> added banner layout and button

.gitignore, app/models/rental.rb
Tested and confirmed error with message
=> Validate rental start date not before today

.gitignore, app/assets/stylesheets/components/_bag_form.scss, app/controllers/rentals_controller.rb, app/policies/rental_policy.rb, app/views/bags/show.html.erb, app/views/rentals/edit.html.erb, app/views/rentals/show.html.erb, config/routes.rb, test/policies/rental_policy_test.rb
=> Created edit and update method for rental, tested

app/controllers/rentals_controller.rb
save was raising exception instead of utilizing if-conditional
=> removed bang operator on rental save that was raising exception

app/controllers/rentals_controller.rb, app/policies/rental_policy.rb
Tested ✔️  redirect currently takes us back to all bags, may be better to bring to all rentals when rentals#index is created
=> Add rental delete action

app/models/rental.rb
=> Validate rental end date not before start date

app/views/rentals/show.html.erb
=> Reformat rental show view

app/controllers/rentals_controller.rb, app/models/rental.rb, app/policies/rental_policy.rb, app/views/rentals/show.html.erb, config/routes.rb
**before accept button**
**after accept button**
=> Create rental accept action

app/views/pages/home.html.erb
@clay-land Could you review it please ?
Centered + Responsive
=> Cards centered

app/controllers/bags_controller.rb, app/models/bag.rb
=> added photo validation to bag model

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_rental_card.scss, app/views/rentals/index.html.erb
=> Styled the requests to be displayed as cards

app/assets/stylesheets/config/_fonts.scss, app/views/bags/new.html.erb
=> Style bags new view

app/views/rentals/show.html.erb
=> Rental total price calculation

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_map.scss, app/javascript/packs/application.js, app/javascript/plugins/init_flatpickr.js, app/models/bag.rb, app/views/bags/_info_window.html.erb, app/views/bags/show.html.erb, package-lock.json, package.json, yarn.lock
=> Flatîcker addition

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_rentals.scss, app/views/rentals/index.html.erb
=> Added some margins on the headers

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_rentals.scss, app/views/rentals/index.html.erb, app/views/shared/_navbar.html.erb
Made navbar fixed on all pages, had to also add some margin-top to the rentals page to fix an overlap with the navbar.
=> Make navbar fixed

app/assets/stylesheets/components/_rental_card.scss
=> Fixed hover color change on 'Cancel this rental'

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/controllers/bags_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/bags/_info_window.html.erb
=> Add map popup windows to markers

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_rental_card.scss, app/views/rentals/index.html.erb
Changed date formatting, fixed buttons class missing.
=> Rentals styling

app/assets/stylesheets/pages/_bag_index.scss, app/assets/stylesheets/pages/_index.scss, app/views/bags/index.html.erb
=> Added color change on cards when current_user is the owner

app/views/bags/index.html.erb
Class 'owned' re-added after mistake in conflict resolution.
=> Removed 'owned' class when resolving a conflict, class re-added

app/assets/stylesheets/pages/_bag_index.scss
=> Removed the border-radius on the image-card

app/javascript/plugins/init_flatpickr.js, app/views/bags/index.html.erb, app/views/bags/show.html.erb, app/views/rentals/show.html.erb
**one day rental**
**multi-day rental**
**bag show page - rate format consistent with rentals - javascript pluralizing not updated**
=> Pluralize days

app/javascript/components/init_proximitysearch.js
=> removed erroneous console.log left over in proximity search js

app/views/rentals/show.html.erb
**Owner View**
**Renter View**
=> reformatted buttons for rental#show views, added back button

app/views/bags/show.html.erb
**Renter View**
**Owner View**
=> added button brand to bag#show page

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_search_bar.scss, app/assets/stylesheets/pages/_index.scss, app/javascript/plugins/init_mapbox.js, app/views/bags/index.html.erb
=> Styling index

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_rental_card.scss, app/views/bags/show.html.erb, app/views/rentals/show.html.erb
=> Test links 1
